### ISSUE TITLE
Wifi connection

### ISSUE THREAD

**Issue by TothCsanad** [LubikR/SynologyUploader#1] opened 2018-03-06 21:08 UTC
Hi,
I tried this app with Sony A5100. It seems that the wifi connection is only created when an app requires it. In STGUploader, wifi connection is established after app startup, but unfortunately this app does not connect. Please help! Thanks :-)

**Comment by LubikR** [comment] 2018-03-06 21:25
Hello,
the application doesn't include a code for wifi connection. If you want to use the application you need to establish wifi connection in another application, for example in OpenMemories:Tweak. I will add this funcionality in future release.

**Comment by TothCsanad** [comment] 2018-03-07 07:51
Thanks! It works but unfortunately the connection fails with 401. This is probably due to my fault.
Looking forward to the upgrade!

**Comment by LubikR** [comment] 2018-03-07 08:00
According to [SynologyAPI](https://global.download.synology.com/download/Document/DeveloperGuide/Synology_Download_Station_Web_API.pdf), 401 means "Account disabled"

**Comment by TothCsanad** [comment] 2018-03-07 08:11
:-) Mysterious

**Comment by TothCsanad** [comment] 2018-03-07 08:20
What protocol does it use? I can not see any refused connection in the log.

**Comment by LubikR** [comment] 2018-03-07 09:23
HTTP at default port 5000. I think the APi is little bit tricky because even I am logged-in I am not able to find any log or something else about it on Synology.
During few days I will publish a release with possibility to use HTPPS and not only on default ports.

**Comment by TothCsanad** [comment] 2018-03-07 09:49
Browsing the [File Station API](https://global.download.synology.com/download/Document/DeveloperGuide/Synology_File_Station_API_Guide.pdf) 401 can be either "Unknown error of file operation" :-(

**Comment by LubikR** [comment] 2018-03-07 11:19
Ups, I see, I sent another API spec, sorry. But, error code 401 is different for different api calls. When the error were returned? During connectionin check in the Settings form or during uploading photos?

**Comment by TothCsanad** [comment] 2018-03-07 11:34
At the beginning of upload.

**Comment by LubikR** [comment] 2018-03-10 09:15
I have checked it many times and get only one error 414 - when file already exists on server. I will do some logging. Meanwhile please try new version and let me know. Thanks

**Comment by TothCsanad** [comment] 2018-03-11 16:47
At the new version, pressing the Upload button immediately restarts the camera :-(

**Comment by TothCsanad** [comment] 2018-03-12 17:49
I just noticed that in version 1.0, it creates a /photoo folder instead of /photo. Destination directory variable returns the last character twice. Maybe that was the reason for the 401 error.

**Comment by LubikR** [comment] 2018-03-14 08:24
Logger added, please try new version 1.2 and send me a log file. Thanks.

**Comment by TothCsanad** [comment] 2018-03-15 15:51
Unfortunately, right after the app started, the camera rebooted. Log is not generated either.

**Comment by LubikR** [comment] 2018-03-15 22:11
I found one stupid issue that application would crash if Port not set. IMHO this issue should be raised for new users only, but please try new version and let me know. Thanks

**Comment by TothCsanad** [comment] 2018-03-16 11:23
Again, it is restarted when uploading. No more log entries...
> [INFO][SettingsActivity] Getting address : ****************:5000 https:false
> [INFO][SettingsActivity] Got maxVersions: SYNO.API.Auth=6, SYNO.FileStation.CheckPermission=3
> [INFO][SettingsActivity] Logged-in OK, sid=000000000000000000000000
> [INFO][SettingsActivity] Check permission OK. Directory=photo
> [INFO][SettingsActivity] Logged-out
> [INFO][SettingsActivity] Saved and Go to MainActivity
> [INFO][MainActivity] Publish progress: Connecting to the server...
> [INFO][MainActivity] Getting address : ****************:5000 https:false
> [INFO][MainActivity] Got maxVersions: SYNO.API.Auth=6, SYNO.FileStation.Upload=3
> [INFO][MainActivity] Logged-in OK, sid=000000000000000000000000
> [INFO][MainActivity] Publish progress: Uploading 1 / 592
> [INFO][MainActivity] UploadVersion=3
> [INFO][MainActivity] Path=/photo/ILCE-5100/06032018

**Comment by LubikR** [comment] 2018-03-17 09:54
Hmm, I think the problem is OutOfMemoryException when creating the object to be uploaded. Your photos are big, right? More than 10MB per one photo?

**Comment by TothCsanad** [comment] 2018-03-17 11:38
The average photo size is 5MB. After formatting, I tried to upload smaller images - with success. Unfortunately, the second upload failed again with 414, but this is obviously because of already uploaded images. Thank you for your help and patience! I see the light ... :-)

**Comment by LubikR** [comment] 2018-03-18 13:58
5MB on my camera is OK, I have got a problem with bigger files than 10MB but my camera is not able to take so big photos. I made some tests and I successfully transfer 56MB file. So please try it. Thanks.

**Comment by TothCsanad** [comment] 2018-03-18 18:03
The new version has flawlessly uploaded ~400MB of images. Only wifi connection is missing ...

**Comment by LubikR** [comment] 2018-03-18 21:45
Great! Many thanks for your tests. I will do something with wifi.

**Comment by LubikR** [comment] 2018-03-23 21:37
Wifi added and new version 1.5. published. Please test it and let me know. Thanks.

**Comment by TothCsanad** [comment] 2018-03-24 08:39
It works perfectly! Great work! I'm also happy with the progress bar. Anyway, would not it be a better solution to show the whole process?

**Comment by LubikR** [comment] 2018-03-24 15:45
Thank you for your feedback! There is always a better way :) And I know I am not designer and also not professional developer. It is fact. So what do you propose? Give me some hints :)

**Comment by LubikR** [comment] 2018-04-02 18:48
The original problem has been resolved so I close this issue. If you have any suggestions please open another one. Thanks.

**Closed by LubikR** 2018-04-02 18:48 UTC
Labels: enhancement
